name: GoAlgorithms
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['^1.13.0', '^1.14.0', '^1.15.0', '^1.16.0', '^1.17.0']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

      - name: Linting
        run: |
          go vet ./...

      - name: Tests
        run: go test -cover ./...
