---
name: go-algorithms
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '^1.13.0'
          - '^1.14.0'
          - '^1.15.0'
          - '^1.16.0'
          - '^1.17.0'
          - '^1.18.0'
          - '^1.19.0'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{matrix.go-version}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest

      - name: Linting
        run: |
          go vet ./...

      - name: Tests
        run: go test -cover ./...
